import sanitizeHtml from 'sanitize-html';

export default function sanitizePostContent(content: string) {
  const output = sanitizeHtml(content, {
    allowedTags: [
      'address',
      'h3',
      'h4',
      'h5',
      'h6',
      'blockquote',
      'dd',
      'div',
      'dl',
      'dt',
      'figcaption',
      'figure',
      'hr',
      'li',
      'ol',
      'p',
      'pre',
      'ul',
      'a',
      'abbr',
      'b',
      'br',
      'cite',
      'code',
      'data',
      'dfn',
      'em',
      'i',
      'mark',
      'ruby',
      's',
      'samp',
      'small',
      'span',
      'strong',
      'sub',
      'sup',
      'time',
      'u',
      'var',
      'caption',
      'col',
      'colgroup',
      'table',
      'tbody',
      'td',
      'tfoot',
      'th',
      'thead',
      'tr',
      'img',
    ],
    nonBooleanAttributes: [
      'abbr',
      'accept',
      'accept-charset',
      'accesskey',
      'action',
      'allow',
      'alt',
      'as',
      'autocapitalize',
      'autocomplete',
      'blocking',
      'charset',
      'cite',
      'class',
      'color',
      'cols',
      'colspan',
      'content',
      'contenteditable',
      'coords',
      'crossorigin',
      'data',
      'datetime',
      'decoding',
      'dir',
      'dirname',
      'download',
      'draggable',
      'enctype',
      'enterkeyhint',
      'fetchpriority',
      'for',
      'form',
      'formaction',
      'formenctype',
      'formmethod',
      'formtarget',
      'headers',
      'height',
      'hidden',
      'high',
      'href',
      'hreflang',
      'http-equiv',
      'id',
      'imagesizes',
      'imagesrcset',
      'inputmode',
      'integrity',
      'is',
      'itemid',
      'itemprop',
      'itemref',
      'itemtype',
      'kind',
      'label',
      'lang',
      'list',
      'loading',
      'low',
      'max',
      'maxlength',
      'media',
      'method',
      'min',
      'minlength',
      'name',
      'nonce',
      'optimum',
      'pattern',
      'ping',
      'placeholder',
      'popover',
      'popovertarget',
      'popovertargetaction',
      'poster',
      'preload',
      'referrerpolicy',
      'rel',
      'rows',
      'rowspan',
      'sandbox',
      'scope',
      'shape',
      'size',
      'sizes',
      'slot',
      'span',
      'spellcheck',
      'src',
      'srcdoc',
      'srclang',
      'srcset',
      'start',
      'step',
      'style',
      'tabindex',
      'target',
      'title',
      'translate',
      'type',
      'usemap',
      'value',
      'width',
      'wrap',
    ],
    disallowedTagsMode: sanitizeHtml.defaults.disallowedTagsMode,
    allowedAttributes: {
      ...sanitizeHtml.defaults.allowedAttributes,
      img: ['src', 'srcset', 'alt', 'title', 'width', 'height', 'loading'],
    },
    selfClosing: ['img', 'br', 'hr'],
    allowedSchemes: sanitizeHtml.defaults.allowedSchemes,
    allowedSchemesByTag: {},
    allowedSchemesAppliedToAttributes: sanitizeHtml.defaults.allowedSchemesAppliedToAttributes,
    allowProtocolRelative: false,
    enforceHtmlBoundary: false,
    parseStyleAttributes: false,
  });

  return output;
}
