/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PostsPostIdSlugImport } from './routes/posts.$postId.$slug'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PostsPostIdSlugRoute = PostsPostIdSlugImport.update({
  path: '/posts/$postId/$slug',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/posts/$postId/$slug': {
      id: '/posts/$postId/$slug'
      path: '/posts/$postId/$slug'
      fullPath: '/posts/$postId/$slug'
      preLoaderRoute: typeof PostsPostIdSlugImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/posts/$postId/$slug': typeof PostsPostIdSlugRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/posts/$postId/$slug': typeof PostsPostIdSlugRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/posts/$postId/$slug': typeof PostsPostIdSlugRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/posts/$postId/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/posts/$postId/$slug'
  id: '__root__' | '/' | '/posts/$postId/$slug'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PostsPostIdSlugRoute: typeof PostsPostIdSlugRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PostsPostIdSlugRoute: PostsPostIdSlugRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/posts/$postId/$slug"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/posts/$postId/$slug": {
      "filePath": "posts.$postId.$slug.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
