/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PostsIndexImport } from './routes/posts.index'
import { Route as PostsPostIdSlugImport } from './routes/posts.$postId.$slug'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PostsIndexRoute = PostsIndexImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRoute,
} as any)

const PostsPostIdSlugRoute = PostsPostIdSlugImport.update({
  id: '/posts/$postId/$slug',
  path: '/posts/$postId/$slug',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsIndexImport
      parentRoute: typeof rootRoute
    }
    '/posts/$postId/$slug': {
      id: '/posts/$postId/$slug'
      path: '/posts/$postId/$slug'
      fullPath: '/posts/$postId/$slug'
      preLoaderRoute: typeof PostsPostIdSlugImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/posts': typeof PostsIndexRoute
  '/posts/$postId/$slug': typeof PostsPostIdSlugRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/posts': typeof PostsIndexRoute
  '/posts/$postId/$slug': typeof PostsPostIdSlugRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/posts/': typeof PostsIndexRoute
  '/posts/$postId/$slug': typeof PostsPostIdSlugRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/posts' | '/posts/$postId/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/posts' | '/posts/$postId/$slug'
  id: '__root__' | '/' | '/posts/' | '/posts/$postId/$slug'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PostsIndexRoute: typeof PostsIndexRoute
  PostsPostIdSlugRoute: typeof PostsPostIdSlugRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PostsIndexRoute: PostsIndexRoute,
  PostsPostIdSlugRoute: PostsPostIdSlugRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/posts/",
        "/posts/$postId/$slug"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/posts/": {
      "filePath": "posts.index.tsx"
    },
    "/posts/$postId/$slug": {
      "filePath": "posts.$postId.$slug.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
