name: Deploy to the server

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: 'sync'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: sync
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 9.5.0
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm i
      - name: Build
        env:
          VITE_CMS_API_ENDPOINT: ${{ secrets.CMS_API_ENDPOINT }}
        run: pnpm run build
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          protocol: ${{ vars.ftp_protocol }}
          port: ${{ vars.ftp_port }}
          local-dir: './dist/'
          server-dir: ${{ vars.ftp_server_dir }}
